const sampleData = {
  products: [
    {
      name: "AMD Ryzen 7 Gaming Computer",
      slug: "gaming-pc-1",
      category: "Gaming",
      description: "AMD Ryzen 7 9800X3D | 32 GB DDR5-6000 | Radeon RX 6700XT",
      images: ["/images/computer_1.JPG"],
      price: 1359.99,
      brand: "New",
      rating: 4.5,
      numReviews: 10,
      stock: 1,
      isFeatured: true,
      banner: "banner-1.jpg",
    },
    {
      name: "Home Office PC",
      slug: "office-pc-1",
      category: "Office",
      description: "Intel i5-10400F | 16 GB DDR4-3200 | MSI Z490 Motherboard",
      images: ["/images/computer_2.JPG"],
      price: 250.0,
      brand: "Refurbished",
      rating: 4.2,
      numReviews: 8,
      stock: 1,
      isFeatured: true,
      banner: "banner-2.jpg",
    },
    {
      name: "Ryzen 5 Gaming Computer",
      slug: "gaming-pc-2",
      category: "Gaming",
      description: "Ryzen 5 5600X | 16 GB DDR4-3600 | 7900XTX",
      images: ["/images/computer_3.JPG"],
      price: 1695.99,
      brand: "Pre-Owned",
      rating: 4.9,
      numReviews: 3,
      stock: 1,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Server Computer",
      slug: "server-pc-1",
      category: "Server",
      description: "Intel i3-14100 | 16GB DDR4-3200 | 8TB Storage",
      images: ["/images/computer_4.JPG"],
      price: 499.95,
      brand: "New",
      rating: 3.6,
      numReviews: 5,
      stock: 1,
      isFeatured: false,
      banner: null,
    },
  ],
};

export default sampleData;
